# Generated by Django 5.1.3 on 2024-12-08 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_month',
            field=models.PositiveIntegerField(max_length=12, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
