# Generated by Django 5.1.3 on 2024-12-08 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentmethod_expiry_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_month',
            field=models.IntegerField(help_text='Enter a valid month (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_year',
            field=models.IntegerField(help_text='Enter a valid year (e.g., 2024)', validators=[django.core.validators.MinValueValidator(2000)]),
        ),
    ]
