# Generated by Django 5.1.3 on 2024-12-08 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymentmethod_expiry_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
