# Generated by Django 5.1.3 on 2024-12-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestackuser',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='buyer', max_length=10),
        ),
    ]
