# Generated by Django 5.1.3 on 2024-12-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_storestackuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestackuser',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10),
        ),
    ]
