# Generated by Django 5.1.3 on 2024-12-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('single-product', 'Single Product'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out For Delivery'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
